const ADD_EXPRESSION = "ADD_EXPRESSION";
const DELETE_EXPRESSION = "DELETE_EXPRESSION";
const DELETE_ALL_EXPRESSIONS = "DELETE_ALL_EXPRESSIONS";
const EDIT_EXPRESSION = "EDIT_EXPRESSION";

export {ADD_EXPRESSION, DELETE_ALL_EXPRESSIONS, DELETE_EXPRESSION, EDIT_EXPRESSION}
